steps:
  - id: 'pull property from json'
    name: gcr.io/$PROJECT_ID/fetchprops-$PROJECT_ID
    args: ['json2files.py', 'https://props-pp.appspot.com/json/propdata/FR', '/workspace/content/biens/']
  - id: 'build site with hugo'
    name: gcr.io/$PROJECT_ID/hugobuild-$PROJECT_ID
    args: ['-v','--destination=public']
  - id: 'deploy to firebase'
    name: gcr.io/$PROJECT_ID/firebasedeploy-$PROJECT_ID
    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']
    
options:
  logging: NONE